  *Day 1 of Pandas*

In [1]:
import pandas as pd

In [6]:

pd.read_csv('population.csv')

,sr.no.,province,division,district,households,population_2023,average_household_size,population_2017,growth_rate,area(km²),...,primary_girls_schools,secondary_boys_schools,secondary_girls_schools,high_boys_schools,high_girls_schools,Intermediate_boys_schools,Intermediate_girls_schools,total_boys_schools,total_girls_schools,total_schools
0,1,Balochistan,Kalat,Awaran,27808,178958,6.44,121821,6.64,29510,...,107,24,13,29,10,2,2,249,132,381
1,2,Balochistan,Kalat,Kalat,33415,272506,8.16,211201,4.35,6622,...,84,23,18,27,17,1,1,269,120,389
2,3,Balochistan,Kalat,Khuzdar,161594,997214,6.17,798896,3.78,35380,...,177,45,46,32,21,6,1,569,245,814
3,4,Balochistan,Kalat,Lasbela,115635,680977,5.89,576271,2.83,15153,...,124,46,29,27,11,4,4,507,168,675
4,5,Balochistan,Kalat,Mastung,43736,313271,7.16,265676,2.79,5896,...,94,24,31,18,18,2,0,268,143,411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,132,Sindh,Shaheed_Benazirabad,Shaheed_Benazirabad,334596,1845102,5.51,1613506,2.27,4502,...,318,47,16,131,38,12,2,2369,374,2743
132,133,Sindh,Sukkur,Ghotki,331132,1772609,5.35,1648708,1.22,6083,...,245,67,22,63,20,6,2,1942,289,2231
133,134,Sindh,Sukkur,Khairpur,452588,2597535,5.74,2405190,1.29,15910,...,390,47,31,191,60,20,2,3134,483,3617
134,135,Sindh,Sukkur,Sukkur,268755,1639897,6.10,1488372,1.63,2512,...,140,26,10,93,29,8,5,1091,184,1275
135,136,Capital_territory,Islamabad,Islamabad,411518,2363863,5.74,2003368,2.80,906,...,0,0,0,345,61,233,51,578,112,690

In [14]:
df=pd.read_csv('population.csv')

In [8]:
# retriving the first five entries
df.head()

,sr.no.,province,division,district,households,population_2023,average_household_size,population_2017,growth_rate,area(km²),...,primary_girls_schools,secondary_boys_schools,secondary_girls_schools,high_boys_schools,high_girls_schools,Intermediate_boys_schools,Intermediate_girls_schools,total_boys_schools,total_girls_schools,total_schools
0,1,Balochistan,Kalat,Awaran,27808,178958,6.44,121821,6.64,29510,...,107,24,13,29,10,2,2,249,132,381
1,2,Balochistan,Kalat,Kalat,33415,272506,8.16,211201,4.35,6622,...,84,23,18,27,17,1,1,269,120,389
2,3,Balochistan,Kalat,Khuzdar,161594,997214,6.17,798896,3.78,35380,...,177,45,46,32,21,6,1,569,245,814
3,4,Balochistan,Kalat,Lasbela,115635,680977,5.89,576271,2.83,15153,...,124,46,29,27,11,4,4,507,168,675
4,5,Balochistan,Kalat,Mastung,43736,313271,7.16,265676,2.79,5896,...,94,24,31,18,18,2,0,268,143,411

In [11]:
#Data frame .. Its a two dimensional collection of data cells. To store data manually its is a dictionary of lists
DF= pd.DataFrame(
    {
       "Name" : ["Ali",'mahnoor','suliman'],
       "Gender" : ["male",'female','male'],
       "age":[23,14,34]
    }
)

In [12]:
DF

      Name  Gender  age
0      Ali    male   23
1  mahnoor  female   14
2  suliman    male   34

In [15]:
df["district"]

0                   Awaran
1                    Kalat
2                  Khuzdar
3                  Lasbela
4                  Mastung
              ...
131    Shaheed_Benazirabad
132                 Ghotki
133               Khairpur
134                 Sukkur
135              Islamabad
Name: district, Length: 136, dtype: object

In [16]:
# how to create a series
Series=pd.Series(['Pakistan','India','UK'],name="countries")

In [17]:
Series

0    Pakistan
1       India
2          UK
Name: countries, dtype: object